name: Test & release

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  test-node:
    uses: bgd-labs/github-workflows/.github/workflows/test-node.yml@main
  release:
    uses: bgd-labs/github-workflows/.github/workflows/release.yml@main
    needs: test-node
  release-node:
    uses: bgd-labs/github-workflows/.github/workflows/release-node.yml@main
    needs: test-node
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
